image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo apt update && sudo apt install -y kali-linux-headless ubuntu-desktop-minimal xvfb fluxbox tigervnc-standalone-server novnc
      sudo systemctl start ssh
      export DISPLAY=:99 && Xvfb :99 -screen 0 1920x1080x24 &
      vncserver :1 -geometry 1920x1080 -depth 24 -localhost no
      websockify -D --web=/usr/share/novnc/ 6080 localhost:5901 &
      cd /workspace && python3 -m pip install -r requirements.txt && ollama serve &
  - command: |
      sleep 10 && ollama pull llama3.1:8b && cd /workspace && python app.py
vscode:
  extensions:
    - ms-vscode-remote.remote-ssh
